CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  goal VARCHAR(5) NOT NULL
);

CREATE TABLE logs (
  id SERIAL PRIMARY KEY,
  user_id INT,
  date TIMESTAMP DEFAULT CURRENT_DATE,
  goal VARCHAR(5) NOT NULL,
  actual VARCHAR(5) NOT NULL
);